### ISSUE TITLE
Doesn't work if there's no domain name

### ISSUE THREAD

**Issue by zapashcanon** [emersion/passwordmaker#7]
Hi,

When I'm viewing some website which don't have a domain name, like [178.170.112.145](http://178.170.112.145) then, the extension stay like this:

![capture du 2016-08-07 19-38-56](https://cloud.githubusercontent.com/assets/16472988/17464100/deab6716-5cd6-11e6-868d-e2d9f9b8fc74.png)

Or with my previous tab domain name - it depends on what I was doing before.

It would be great if the extension could detect whether it's an IP or a domain name and then use it in both case. :)

**Comment by emersion** [comment]
This is the repo for the WebExtension, not the legacy Firefox extension. Please report issues to https://github.com/emersion/firefox-passwordmaker. I'm likely to switch the old Firefox extension to this cross-browser implementation soon.

Though, there was a bug in this implementation too that caused `127.0.0.1` to be changed to `0.1`. It's now fixed.

**Comment by zapashcanon** [comment]
Ah yep, sorry !

> Though, there was a bug in this implementation too that caused 127.0.0.1 to be changed to 0.1. It's now fixed.

I knew it but I wanted to see if you'll see it. :p 

I'm going to report it on firefox-passwordmaker too then.

Thanks ! :)
